### ISSUE TITLE
https://dock.orion3.space/releases/dock_stable.tgz out of date with github stable branch

### ISSUE THREAD

**Issue by shopeonarope** [0rion3/dock#4]
Following installation option 1 instructions results in downloading an old version:

```
$ date; curl -s https://dock.orion3.space/releases/dock_stable.tgz | tar --to-stdout -xzvf - dock_9112d9f/bin/dock | sha256sum; \
curl -s https://raw.githubusercontent.com/0rion3/dock/stable/bin/dock | sha256sum
Fri Jul 15 03:38:15 PM MDT 2022
dock_9112d9f/bin/dock
596b6b412d8d29c1732e26200c6d54ab419cdb347abf551d80bf35c02156997a  -
eb7e981414cf970b2e7bc921d753f6136e8c74e9da27c138e55d3dddaa2cc587  -
```

~Github provides zip and tgz options to download branches or tags:~
~- curl -o dock_stable.zip https://github.com/0rion3/dock/archive/refs/heads/stable.zip~
~- curl -o dock_stable.tgz https://github.com/0rion3/dock/tarball/stable~
~The website could redirect to one of those then it's always using the source of truth or the instructions could use them directly.~
nm, disregard my suggestion, that doesn't account for the submodules.

**Comment by 0rion3** [comment]
Indeed, it never suggested downloading the zip from Github, only cloning the repo and the initializing and updating sub-modules. Please let me know if you find any place like that anywhere in the documentation.
